<div class="jumbotron">
    <h2><?php echo sprintf($this->translate('Development + Operations = %sDevOps%s'), '<span class="zf-green">', '</span>') ?></h2>
    <p><?php echo sprintf($this->translate('Devops are your modern day Webmasters. The person who can do it all. Develop a website, install a webserver, stand up a database and deploy code to production.')) ?></p>
    <p><a class="btn btn-success btn-lg" href="#" target="_blank"><?php echo $this->translate('See How I Can Help You') ?> &raquo;</a></p>
</div>
